language: java
jdk:
  - openjdk11
services:
  - postgresql
before_script:
  - psql -c 'create database testdb;' -U postgres
env:
  - DATABASE_URL=jdbc:postgresql://localhost:5432/hirehustle
script:
  - ./mvnw clean verify
